CREATE TABLE "Players" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" VARCHAR(36),
  "firstName" VARCHAR,
  "lastName" VARCHAR,
  "position" VARCHAR,
  "roleId" INT,
  "teamId" INT,
  "serieaPlayer" BOOL
);

CREATE TABLE "PlayersDetails" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" VARCHAR(36),
  "playerId" INT,
  "height" DECIMAL,
  "weight" DECIMAL,
  "dateOfBirth" DATE,
  "nationality" VARCHAR,
  "imgUrl" VARCHAR
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" VARCHAR(36),
  "rolePrincipal" VARCHAR,
  "roleDetail" VARCHAR
);

CREATE TABLE "PlayersValues" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" VARCHAR(36),
  "playerId" INT,
  "eurocentValue" INT
);

CREATE TABLE "Teams" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uid" VARCHAR(36),
  "teamName" VARCHAR,
  "coach" VARCHAR,
  "stadium" VARCHAR,
  "positionInLeague" INT
);

ALTER TABLE "Players" ADD FOREIGN KEY ("roleId") REFERENCES "Roles" ("id");

ALTER TABLE "Players" ADD FOREIGN KEY ("teamId") REFERENCES "Teams" ("id");

ALTER TABLE "PlayersDetails" ADD FOREIGN KEY ("playerId") REFERENCES "Players" ("id");

ALTER TABLE "PlayersValues" ADD FOREIGN KEY ("playerId") REFERENCES "Players" ("id");
